VAULT_ADDR: http://10.10.2.5:30000
ingress:
  tls: []
  hosts:
  - paths: []
    host: chart-example.local
  enabled: false
  annotations: {}
securityContext: {}
replicaWorkersCount: 1
service:
  type: ClusterIP
  port: 80
image:
  pullPolicy: Always
  tag: b2c2
  repository: ayhamkassab/caliper
args:
  second: manager
  first: launch
serviceAccount:
  create: true
  name: 
fullnameOverride: 
podSecurityContext: {}
nodeSelector: {}
tolerations: []
ENDORSING_ORG_NAMES: "carrier manufacturer buyer"
nameOverride: 
VAULT_TOKEN: s.4fdn3q75Q9F4HfN5c2j5wWhc
replicaMasterCount: 1
affinity: {}
resources: {}
imagePullSecrets: []
